server:
  port: 8080

spring:
  application:
    name: wallet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

